spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
